# Generated by Django 5.1.4 on 2025-01-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_director',
            new_name='review_author',
        ),
    ]
