# Generated by Django 5.1.4 on 2025-01-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_review_review_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='realese_date',
            new_name='release_date',
        ),
    ]
